version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: github-actions

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: pnpm
    ignore:
      - dependency-name: '@biomejs/biome'
      - dependency-name: '@astrojs/compiler-rs'
        versions: ['>=0.4.0']
