name = "yagiz"
compatibility_date = "2026-03-21"
compatibility_flags = [ "nodejs_compat" ]
send_metrics = false
preview_urls = true
main = "@astrojs/cloudflare/entrypoints/server"

[placement]
mode = "smart"

[[d1_databases]]
binding = "newsletter"
database_name = "newsletter"
database_id = "33ad2d37-f48c-4033-86fd-81c7ade04178"

[assets]
binding = "ASSETS"
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true

[[send_email]]
name = "email"
allowed_sender_addresses = ["contact@newsletter.yagiz.co"]
